name: Publish contract
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  publish:
    uses: sneat-co/cicd/.github/workflows/npm-publish.yml@main
    with:
      working-directory: frontend
      install-command: pnpm install --no-frozen-lockfile --ignore-scripts
      build-command: pnpm exec nx build ext-taxus-contract
      publish-command: pnpm exec nx release --yes && npm access set status=public @sneat/extension-taxus-contract && git push --follow-tags
    secrets: inherit
